# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0dc02bc3bf08d687bcdd8d1f158d3a88515b0d355a93ce4cc7ecdbb5da318ed40119e7b45167f388f0fdfb29ad4bd4e3cef65428a14170e97a01031dd5ef13a9

test:
  secret_key_base: 885c64b2698cb1fb6be549b4d052bb3273695b550aa8d592cee0d6e75c7131b9f255a67cccf7c10132b95c4f2b62e8547416bafd79359304b84d62e6bae01d76

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
